#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved.

"""Fails when `exec`/`eval`/`compile` is handed a string built by interpolation.

The pattern this exists for is the one PR unslothai/unsloth-zoo#1083 removed:

    exec(f"import transformers.models.{model_type}.modeling_{model_type}")

`model_type` came off a downloaded config.json, so a hostile model repo reached an
`exec`. Bare `exec(source)` where `source` is generated by `inspect.getsource` is
normal and heavily used here, so it is NOT flagged - what is flagged is a first
argument that is an f-string, a string concatenation, a `%` format or a `.format()`
call, because that is the shape where a value becomes syntax.

Reviewed exceptions live in `dynamic_exec_allowlist.json` next to this file. Entries
are keyed on (path, enclosing qualname, sha256 of the normalised call source) rather
than a line number, so they survive edits elsewhere in the file but not edits to the
call itself: change the call and you have to re-justify it.

Stdlib only, so it can run in a lint job that installs nothing.

Usage:
    python scripts/lint_dynamic_exec.py                 # check the package
    python scripts/lint_dynamic_exec.py --self-test     # check the checker
    python scripts/lint_dynamic_exec.py --update        # rewrite the allowlist
    python scripts/lint_dynamic_exec.py --paths a.py b.py
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import sys
from pathlib import Path


SINKS = ("exec", "eval", "compile")

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST_PATH = Path(__file__).resolve().parent / "dynamic_exec_allowlist.json"

# Directories scanned by default. Tests are excluded: they legitimately keep the
# removed exec/eval around as an oracle to prove the replacement matches it.
# `unsloth-cli.py` is a tracked entrypoint that the adjacent compile and ruff steps
# already cover; leaving it out meant an interpolated call added there was never
# visited by the security gate at all.
DEFAULT_TARGETS = (
    "unsloth",
    "studio",
    "unsloth_cli",
    "scripts",
    "cli.py",
    "unsloth-cli.py",
)


class ScanError(Exception):
    """A file the checker could not finish reading. The gate fails rather than guess."""


def _relative(path: Path) -> str:
    """Repo-relative where possible; absolute for the self-test's temp files.

    Always forward slashes: the allowlist is committed, and a Windows checkout that
    regenerated it with backslashes would rewrite every entry.
    """
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


# Methods that build a string out of values. `format_map` is `format` with the
# fields taken from a mapping instead of keyword arguments - same interpolation,
# same shape, so leaving it out let `exec("import {m}".format_map(cfg))` through.
_BUILDERS = ("format", "format_map", "join")

# Conversions that hand the same source on in another type. `exec`, `eval` and
# `compile` all accept bytes as well as str, so `exec(f"import {name}".encode())`
# executes exactly the payload the f-string built.
_CONVERSIONS = ("encode", "decode")

# Constructors that hand the same source on in another type. Same argument as
# `_CONVERSIONS`, spelled as a call instead of a method: `bytes(s, "utf-8")` is
# documented as `s.encode("utf-8")`, `str(s)` on a str is the str, and `exec`
# compiles any of them. Verified on CPython 3.13: `exec(bytes(f"import {name}",
# "utf-8"))`, `exec(bytearray(...))` and `exec(memoryview(...))` all import.
_CONSTRUCTORS = ("bytes", "bytearray", "str", "memoryview")

# Each constructor also takes its source by keyword, verified on CPython 3.13:
# `bytes(source = ..., encoding = ...)` and `str(object = ...)` both build the same
# value a positional call would, so reading only `args[0]` missed them.
_CONSTRUCTOR_SOURCE_KEYWORD = {
    "bytes": "source", "bytearray": "source",
    "str": "object", "memoryview": "object",
}


def _constructor_name(function: ast.AST) -> str | None:
    """`bytes` for both `bytes(...)` and `builtins.bytes(...)`, else None."""
    if isinstance(function, ast.Name) and function.id in _CONSTRUCTORS:
        return function.id
    if isinstance(function, ast.Attribute) and function.attr in _CONSTRUCTORS:
        if isinstance(function.value, ast.Name) and function.value.id == "builtins":
            return function.attr
    return None


def _constructor_source(node: ast.Call, name: str) -> ast.AST | None:
    """The value a constructor is converting, positional or by keyword."""
    if node.args:
        return node.args[0]
    wanted = _CONSTRUCTOR_SOURCE_KEYWORD.get(name)
    for keyword in node.keywords:
        if keyword.arg == wanted:
            return keyword.value
    return None


def _is_interpolated(node: ast.AST, resolve = None) -> str | None:
    """Returns why `node` is a built string, or None if it is not one.

    `resolve` maps a bare name to the reason it is tainted, or None. It is passed
    at a sink and not while binding, so this stays one level of indirection: a
    name is resolved where it is executed, never chained into another binding.
    """
    # `exec(payload := f"import {name}")` executes the f-string; the walrus is an
    # `ast.NamedExpr` wrapper around it, not a different value.
    while isinstance(node, ast.NamedExpr):
        node = node.value
    if isinstance(node, ast.Name):
        return resolve(node.id) if resolve is not None else None
    if isinstance(node, ast.JoinedStr):
        # An f-string with no placeholders is just a literal.
        if any(isinstance(v, ast.FormattedValue) for v in node.values):
            return "f-string"
        return None
    if isinstance(node, ast.BinOp):
        if isinstance(node.op, ast.Mod):
            return "%-format"
        if isinstance(node.op, ast.Add):
            return "string concatenation"
    if isinstance(node, ast.Call):
        function = node.func
        if isinstance(function, ast.Attribute):
            if function.attr in _BUILDERS:
                return f".{function.attr}()"
            if function.attr in _CONVERSIONS:
                # `str.encode(s)` is the unbound descriptor spelling of `s.encode()`.
                # There the source is the first argument and the receiver is the type,
                # so unwrapping the receiver looked at the name `str` and found nothing.
                if isinstance(function.value, ast.Name):
                    if function.value.id in _CONSTRUCTORS:
                        return (
                            _is_interpolated(node.args[0], resolve)
                            if node.args else None
                        )
                # Unwrap the receiver: the conversion changes the type, not the syntax.
                return _is_interpolated(function.value, resolve)
        constructor = _constructor_name(function)
        if constructor is not None:
            source = _constructor_source(node, constructor)
            if source is not None:
                return _is_interpolated(source, resolve)
        # `exec("import MODULE".replace("MODULE", name))` splices a value into a
        # template that is right there in the file, which is the `.format()` shape
        # spelled differently. Restricted to a literal receiver on purpose: the
        # `exec(inspect.getsource(f).replace(...))` idiom this repo is built on has a
        # variable receiver and is not this shape. Verified: adding plain "replace"
        # to _BUILDERS instead raises 5 findings here and 5 in unsloth, all of them
        # that idiom; this branch raises none.
        if isinstance(function, ast.Attribute) and function.attr == "replace":
            if isinstance(function.value, ast.Constant) and isinstance(function.value.value, str):
                return ".replace() on a literal"
    return None


def _sink_name(function: ast.AST) -> str | None:
    """The sink this call target names, if any.

    Both `exec(...)` and `builtins.exec(...)` execute. Matching only `ast.Name` meant
    the second form passed the lint with zero findings.
    """
    if isinstance(function, ast.Name) and function.id in SINKS:
        return function.id
    if isinstance(function, ast.Attribute) and function.attr in SINKS:
        if isinstance(function.value, ast.Name) and function.value.id == "builtins":
            return f"builtins.{function.attr}"
    return None


def _source_argument(node: ast.Call, sink: str) -> ast.AST | None:
    """The source argument of a sink call, whether positional or by keyword.

    `exec` and `eval` take their source positional-only, so for those it is always
    `args[0]`. `compile` does not: its signature is
    `compile(source, filename, mode, ...)` with no `/`, so
    `compile(source = f"y = {x}", filename = "<x>", mode = "exec")` compiles exactly
    the same payload with `node.args` empty. Checking only `args[0]` meant that call
    was skipped entirely. `studio/backend/core/inference/tools.py` already resolves
    sink arguments this way.
    """
    if node.args:
        return node.args[0]
    if sink.rpartition(".")[2] == "compile":
        for keyword in node.keywords:
            if keyword.arg == "source":
                return keyword.value
    return None


class _Visitor(ast.NodeVisitor):
    def __init__(self, path: Path):
        self.path = path
        self.scope: list[str] = []
        self.findings: list[dict] = []
        # name -> reason, for locals bound to a built string in the current scope.
        self.tainted: list[dict[str, str]] = [{}]

    def _qualname(self) -> str:
        return ".".join(self.scope) if self.scope else "<module>"

    def _enter(self, node):
        self.scope.append(node.name)
        # A fresh scope: a name built in one function says nothing about the same name
        # in another.
        self.tainted.append({})
        self.generic_visit(node)
        self.tainted.pop()
        self.scope.pop()

    visit_FunctionDef = _enter
    visit_AsyncFunctionDef = _enter
    visit_ClassDef = _enter

    def visit_Assign(self, node: ast.Assign):
        """Tracks `payload = f"...{x}..."` so `exec(payload)` is still caught.

        One level of local indirection, which is all it took to defeat the previous
        version: moving the interpolation onto the line above is a two-line refactor
        that leaves the vulnerability shape exactly as it was. Rebinding a tracked name
        to something that is not a built string clears it, so this does not accumulate
        false positives.
        """
        reason = _is_interpolated(node.value)
        # Runtime order, not source order. The right hand side is evaluated first,
        # then the targets are assigned left to right, and a target that is not a
        # plain name has expressions of its own that run at its turn. So in
        # `payload = table[exec(payload)] = f"import {name}"` the f-string reaches
        # `payload` before the subscript is evaluated, and the `exec` sees it.
        # Visiting every target before binding any of them missed that.
        self.visit(node.value)
        for target in node.targets:
            self.visit(target)
            self._bind(target, reason)

    def visit_AnnAssign(self, node: ast.AnnAssign):
        """Same tracking for `payload: str = f"...{x}..."`.

        An annotated assignment is an `ast.AnnAssign`, a sibling of `ast.Assign`, and
        `NodeVisitor` dispatches on the exact class name - so `visit_Assign` never saw
        it and adding a type hint was enough to hide the binding. `node.value` is
        optional: a bare `payload: str` declares nothing and must leave taint alone
        rather than clear it.
        """
        reason = _is_interpolated(node.value) if node.value is not None else None
        if node.value is not None:
            self.visit(node.value)
            self._bind(node.target, reason)
        # The annotation is evaluated AFTER the store, so at module or class scope,
        # where annotations are evaluated at all, a runtime annotation observes the
        # new binding: `payload: exec(payload) = f"import {name}"` executes the value
        # that was just assigned. Confirmed on CPython 3.13.
        self.visit(node.annotation)
        self.visit(node.target)

    def visit_NamedExpr(self, node: ast.NamedExpr):
        """`(payload := f"import {name}")` as a statement, then `exec(payload)`.

        Unwrapping the walrus at the sink only helps when the named expression is
        handed straight to it. Standing on its own it is exactly the one level of
        local indirection already tracked for `payload = f"..."`, and it is a
        parenthesis away from that spelling, so it has to bind the same way.
        """
        self.generic_visit(node)
        self._bind(node.target, _is_interpolated(node.value))

    def _bind(self, target: ast.AST, reason: str | None) -> None:
        if not isinstance(target, ast.Name):
            return
        if reason is None:
            self.tainted[-1].pop(target.id, None)
        else:
            self.tainted[-1][target.id] = f"{reason} via `{target.id}`"

    def visit_Call(self, node: ast.Call):
        sink = _sink_name(node.func)
        argument = _source_argument(node, sink) if sink is not None else None
        if argument is not None:
            # The taint lookup has to happen wherever the unwrapping stops, not only
            # when the argument is a bare name: `payload = f"import {name}"` followed
            # by `exec(payload.encode())` executes the same bytes and used to unwrap
            # to an `ast.Name` that nothing then looked up.
            reason = _is_interpolated(argument, self.tainted[-1].get)
            if reason is not None:
                self.findings.append(
                    {
                        "path": _relative(self.path),
                        "qualname": self._qualname(),
                        "sink": sink,
                        "reason": reason,
                        "line": node.lineno,
                        "hash": _call_hash(node),
                    }
                )
        self.generic_visit(node)


def _call_hash(node: ast.Call) -> str:
    """Hashes the call, canonicalised through `ast.unparse`.

    Line numbers drift whenever anything above the call changes; the call itself does
    not. Unparsing means reindenting, rewrapping or reflowing the call does not
    invalidate a justification, while changing what is interpolated does.
    """
    return hashlib.sha256(ast.unparse(node).encode("utf-8")).hexdigest()[:16]


def scan_file(path: Path) -> list[dict]:
    # A hard CI gate must not fall over on something that is not a readable file. A
    # dangling symlink, a directory named `*.py`, or a symlink to one all reach here
    # through rglob and raise out of read_text, failing the build for a reason that has
    # nothing to do with dynamic execution.
    try:
        source = path.read_text(encoding = "utf-8", errors = "replace")
    except OSError:
        return []
    try:
        tree = ast.parse(source, filename = str(path))
    except (SyntaxError, ValueError) as error:
        # A file that cannot be parsed has not been checked, and reporting it as clean
        # is the same bypass as swallowing a RecursionError. The comment here used to
        # defer to compileall in the same job, but both syntax-reporting steps in
        # lint-ci.yml are `continue-on-error: true`, so nothing else fails the build.
        # ValueError covers a source containing a NUL byte, which ast.parse rejects
        # separately from a syntax error.
        raise ScanError(
            f"{_relative(path)}: could not be parsed ({error.__class__.__name__}), so "
            f"it was not checked for interpolated dynamic execution"
        ) from None
    visitor = _Visitor(path)
    try:
        visitor.visit(tree)
    except RecursionError:
        # A deeply nested expression can exhaust the stack during the walk, after parse
        # succeeded. Returning [] here reported the file as clean, which is a bypass:
        # 500 nested `not` in front of an interpolated exec compiled fine and the gate
        # passed with zero findings. An unfinishable walk is an unknown, and a security
        # gate reports an unknown as a failure, not as a pass.
        raise ScanError(
            f"{_relative(path)}: too deeply nested to walk, so this file could not be "
            f"checked for interpolated dynamic execution"
        ) from None
    return visitor.findings


def scan(paths: list[Path]) -> tuple[list[dict], list[str]]:
    """Findings, plus the files the checker could not finish. Both fail the gate."""
    findings, errors = [], []
    for path in sorted(paths):
        try:
            findings.extend(scan_file(path))
        except ScanError as error:
            errors.append(str(error))
    return findings, errors


def collect_paths(targets: list[str]) -> tuple[list[Path], list[str]]:
    """Files to scan, plus the targets that resolved to nothing.

    A target that is neither a Python file nor a directory used to be dropped in
    silence, so renaming a file in `DEFAULT_TARGETS` or mistyping a `--paths`
    argument left the gate passing over less code than it claims to cover. Reduced
    coverage that still exits 0 is the failure this whole checker exists to avoid,
    so an unresolvable target is reported rather than skipped.
    """
    paths, missing = [], []
    for target in targets:
        root = REPO_ROOT / target
        if root.is_file() and root.suffix == ".py":
            paths.append(root)
        elif root.is_dir():
            # `is_file()` on each hit, so a directory named `foo.py` and a symlink that
            # points at one are skipped rather than read.
            paths.extend(
                p
                for p in root.rglob("*.py")
                if p.is_file() and "tests" not in _exclusion_parts(p, root)
            )
        else:
            missing.append(
                f"{target}: requested scan target does not exist, so nothing under it "
                f"was checked"
            )
    return paths, missing


def _exclusion_parts(path: Path, root: Path) -> tuple[str, ...]:
    """Path components the tests exclusion is matched against.

    Repo-relative when the file is in the repo, so the default scan keeps excluding
    `<target>/tests/...` exactly as before. A directory passed through `--paths` may
    sit outside the checkout - a pytest tmp_path, a vendored tree - and
    `relative_to(REPO_ROOT)` raises `ValueError` for every file under it, which took
    the whole run down with a traceback before any finding was printed. External
    single files already worked, so this only makes directories agree with them.
    """
    for base in (REPO_ROOT, root):
        try:
            return path.relative_to(base).parts
        except ValueError:
            continue
    return path.parts


def load_allowlist() -> dict[str, dict]:
    if not ALLOWLIST_PATH.exists():
        return {}
    data = json.loads(ALLOWLIST_PATH.read_text(encoding = "utf-8"))
    return {key_of(entry): entry for entry in data.get("allowed", [])}


def key_of(finding: dict) -> str:
    """Identity of a reviewed call: where it is, and what it is.

    The hash alone is not an identity. Two different call sites with byte-identical
    source share a hash, so approving one approved the other, and copying an
    allowlisted call into a function with attacker-controlled inputs inherited its
    justification without review. The location is half of what was reviewed, so it is
    half of the key.
    """
    return f"{finding['path']}::{finding['qualname']}::{finding['hash']}"


def write_allowlist(findings: list[dict], reason: str) -> None:
    existing = load_allowlist()
    allowed = []
    for finding in findings:
        previous = existing.get(key_of(finding), {})
        allowed.append(
            {
                "path": finding["path"],
                "qualname": finding["qualname"],
                "sink": finding["sink"],
                "kind": finding["reason"],
                "hash": finding["hash"],
                "reason": previous.get("reason", reason),
            }
        )
    allowed.sort(key = lambda e: (e["path"], e["qualname"], e["hash"]))
    ALLOWLIST_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "Reviewed exec/eval/compile calls whose first argument is a built "
                    "string. Keyed on a hash of the call's own source, so editing the "
                    "call requires re-reviewing it. Regenerate with "
                    "scripts/lint_dynamic_exec.py --update, then replace every REVIEW "
                    "ME with why the interpolated value cannot be attacker controlled."
                ),
                "allowed": allowed,
            },
            indent = 2,
        )
        + "\n"
    )


# --- self test ---------------------------------------------------------------

_BAD = """
def f(model_type):
    exec(f"import transformers.models.{model_type}")
    eval("torch." + name)
    compile("x = %s" % value, "<x>", "exec")
    exec("a.{}.b".format(name))
    compile(source = f"y = {value}", filename = "<x>", mode = "exec")
    exec("import {module}".format_map(values))
    exec(f"import {name}".encode())
    annotated: str = f"import {name}"
    exec(annotated)
    exec(bytes(f"import {name}", "utf-8"))
    exec(payload := f"import {name}")
    exec("import MODULE".replace("MODULE", name))

def g(name):
    payload = f"import {name}"
    exec(payload.encode())

def h(name):
    payload = f"import {name}"
    payload: object = exec(payload)

def i(name):
    payload = f"import {name}"
    payload = exec(payload)

def j(name):
    (payload := f"import {name}")
    exec(payload)

def k(name):
    table = {}
    payload = table[exec(payload)] = f"import {name}"

def l(name):
    exec(bytes(source = f"import {name}", encoding = "utf-8"))
    exec(str(object = f"import {name}"))
    exec(str.encode(f"import {name}"))

annotated_at_module: exec(annotated_at_module) = f"import {NAME}"
"""

_GOOD = """
import inspect

def f(cls):
    source = inspect.getsource(cls)
    exec(source, globals())
    eval(compile(source, "<x>", "eval"))
    exec(f"plain f-string with no placeholders")
    module.exec(f"{name}")          # not the builtin
    exec()                          # no arguments
    exec(source.replace("def a", "def b"), globals())   # variable receiver
    exec(str(source))               # str() of a name is not interpolation
"""


def self_test() -> int:
    import tempfile

    failures = []
    with tempfile.TemporaryDirectory() as directory:
        bad = Path(directory) / "bad.py"
        bad.write_text(_BAD)
        findings = scan_file(bad)
        kinds = sorted(f["reason"] for f in findings)
        expected = [
            "%-format",
            ".format()",
            ".format_map()",
            ".replace() on a literal",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string via `annotated_at_module`",
            "f-string via `annotated`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "string concatenation",
        ]
        if kinds != expected:
            failures.append(f"expected {expected}, got {kinds}")
        if any(
            f["qualname"] not in ("f", "g", "h", "i", "j", "k", "l", "<module>")
            for f in findings
        ):
            failures.append(f"qualname wrong: {[f['qualname'] for f in findings]}")

        good = Path(directory) / "good.py"
        good.write_text(_GOOD)
        clean = scan_file(good)
        if clean:
            failures.append(f"false positives: {clean}")

        # The hash must ignore reformatting but not a changed interpolation.
        one = Path(directory) / "one.py"
        one.write_text('def f(x):\n    exec(f"import {x}")\n')
        two = Path(directory) / "two.py"
        two.write_text('def f(x):\n    exec(\n        f"import {x}"\n    )\n')
        three = Path(directory) / "three.py"
        three.write_text('def f(x):\n    exec(f"import os; {x}")\n')
        h1 = scan_file(one)[0]["hash"]
        h2 = scan_file(two)[0]["hash"]
        h3 = scan_file(three)[0]["hash"]
        if h1 != h2:
            failures.append("reformatting changed the hash")
        if h1 == h3:
            failures.append("changing the interpolation did not change the hash")

        # An AST too deep to walk must fail the gate, not report the file clean.
        deep = Path(directory) / "deep.py"
        deep.write_text(
            "def f(user):\n    x = " + "not " * 500 + "True\n" '    exec(f"import {user}")\n'
        )
        try:
            scan_file(deep)
            failures.append("a file too deep to walk was reported clean")
        except ScanError:
            pass
        _, errors = scan([deep])
        if len(errors) != 1:
            failures.append(f"scan() should surface the unscannable file, got {errors}")

        # A directory outside the repo must scan rather than crash on relative_to.
        external = Path(directory) / "external"
        external.mkdir()
        (external / "x.py").write_text('def f(m):\n    exec(f"import {m}")\n')
        collected, missing = collect_paths([str(external)])
        found, errors = scan(collected)
        errors += missing
        if len(found) != 1 or errors:
            failures.append(f"external directory not scanned: {found}, {errors}")

        # A file that cannot be parsed has not been checked, so it must not read as
        # clean. Both syntax-reporting steps in lint-ci.yml are continue-on-error, so
        # nothing else in the job would fail the build for it.
        broken = Path(directory) / "broken.py"
        broken.write_text("def f(:\n")
        try:
            scan_file(broken)
            failures.append("a file that does not parse was reported clean")
        except ScanError:
            pass

        # ast.parse rejects a NUL byte with ValueError rather than SyntaxError.
        nul = Path(directory) / "nul.py"
        nul.write_bytes(b"x = 1\x00\n")
        try:
            scan_file(nul)
            failures.append("a file containing a NUL byte was reported clean")
        except ScanError:
            pass

        # A target that resolves to nothing means reduced coverage, not a clean run.
        _, absent = collect_paths(["no_such_target_xyz.py"])
        if len(absent) != 1:
            failures.append(f"a missing scan target was skipped in silence: {absent}")
        _, present = collect_paths([str(external)])
        if present:
            failures.append(f"an existing target was reported missing: {present}")

    for failure in failures:
        print(f"self-test: {failure}", file = sys.stderr)
    if failures:
        print(f"FAIL: {len(failures)} self-test failure(s)", file = sys.stderr)
        return 1
    print("self-test: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument("--self-test", action = "store_true")
    parser.add_argument(
        "--update", action = "store_true", help = "rewrite the allowlist from the current tree"
    )
    parser.add_argument(
        "--paths",
        nargs = "*",
        default = None,
        help = "files or directories to scan (default: the package)",
    )
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    targets = args.paths if args.paths else list(DEFAULT_TARGETS)
    collected, missing = collect_paths(targets)
    findings, errors = scan(collected)
    # A target that resolved to nothing is reported with the unscannable files: in
    # both cases the gate looked at less code than it was asked to.
    errors += missing

    if args.update:
        # An allowlist written from an incomplete scan would bake in the gap.
        if errors:
            for error in errors:
                print(f"scan error: {error}", file = sys.stderr)
            print(
                "\nFAIL: refusing to rewrite the allowlist from an incomplete scan.",
                file = sys.stderr,
            )
            return 1
        write_allowlist(findings, reason = "REVIEW ME")
        print(f"wrote {len(findings)} entries to {ALLOWLIST_PATH.name}")
        return 0

    allowlist = load_allowlist()
    unreviewed = [f for f in findings if key_of(f) not in allowlist]
    pending = [
        entry
        for entry in allowlist.values()
        if entry.get("reason", "").strip().upper() in ("", "REVIEW ME")
    ]
    # Staleness is only meaningful over the whole tree: with --paths the scan is a
    # subset, so every entry outside it would look stale.
    seen = {key_of(f) for f in findings}
    stale = [] if args.paths else [entry for key, entry in allowlist.items() if key not in seen]

    for finding in unreviewed:
        print(
            f"{finding['path']}:{finding['line']}: {finding['sink']}() is handed a "
            f"{finding['reason']} (in {finding['qualname']})",
            file = sys.stderr,
        )
    for entry in pending:
        print(
            f"{entry['path']}: {entry['sink']}() in {entry['qualname']} is allowlisted "
            f"but has no justification",
            file = sys.stderr,
        )
    for entry in stale:
        print(
            f"{entry['path']}: allowlist entry for {entry['sink']}() in "
            f"{entry['qualname']} no longer matches any call - re-run --update",
            file = sys.stderr,
        )
    for error in errors:
        print(f"scan error: {error}", file = sys.stderr)

    if unreviewed or pending or stale or errors:
        print(
            f"\nFAIL: {len(unreviewed)} unreviewed, {len(pending)} unjustified, "
            f"{len(stale)} stale, {len(errors)} unscannable.\n"
            f"Fix the call, or run --update and write down why the interpolated value "
            f"cannot be attacker controlled.",
            file = sys.stderr,
        )
        return 1

    print(f"ok: {len(findings)} interpolated dynamic-execution call(s), all reviewed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
